### ISSUE TITLE
UUID issue

### ISSUE THREAD

**Issue by krewllobster** [morkid/paginate#3]
Hi there, this seems to work fine as long as the ids of the paginated entities in questions are `uints`.

I've implemented a custom data-type similar to [this medium article](https://medium.com/wesionary-team/implementation-of-uuid-and-binary-16-in-gorm-v2-1c329c352c91) that stores a BINARY(16) value as the id and provides helper methods to convert a string uuid to a BINARY(16) and back.

This paginate lib seems to have an issue with the implementation and I'm not sure why. I've got it working beautifully with entities with an INT primaryKey, but I get the following panic error:

```
2021/04/26 16:03:58 http: panic serving 127.0.0.1:61948: uuid: Parse(paginated): invalid UUID length: 9
goroutine 156 [running]:
net/http.(*conn).serve.func1(0xc0003c25a0)
        /usr/local/Cellar/go/1.15.2/libexec/src/net/http/server.go:1801 +0x147
panic(0x1ca1340, 0xc000786a80)
        /usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:975 +0x3e9
github.com/google/uuid.MustParse(0xc00024c52c, 0x9, 0x0, 0x0)
```

There is a ParseUUID function on the custom `BinaryUUID` data type defined as follows:
```
func ParseUUID(id string) BinaryUUID {
	fmt.Println("Attempting to parse: ", id)
	return BinaryUUID(uuid.MustParse(id))
}
```

And the panic throws right after this function logs: "Attempting to parse: pagination". So for some reason, the string "pagination" is being interpreted as the id field of the selected entities? I'm not sure I understand 100% what is going on though.

**Comment by morkid** [comment]
Have you tried getting a response without pagination?

**Comment by krewllobster** [comment]
Yep, Gorm calls work fine and automatically convert the binary(16) uuid into a string for the id field when JSON marshaled

**Comment by morkid** [comment]
I wonder what is inside the BinaryUUID and when is the ParseUUID function called?  
if your goal is to find a way to store the value as uuid and serve it back as a string  
please check these points:

- Make sure field name, json name, property name must be the same ([see reference](https://github.com/morkid/paginate#limitations)).
- I've implemented uuid in several projects with postgres but never saved it as binary(16). Maybe you can try with varchar.
- I suggest using the [`BeforeCreate hook`](https://medium.com/wesionary-team/.implementation-of-uuid-and-binary-16-in-gorm-v2-1c329c352c91#2cf4) instead of `UUID_TO_BIN(UUID())`.
- All `filters` params on paginate only work with string, number, boolean, null and array.  
I think it will be your next problem ([see reference](https://www.geeksforgeeks.org/json-data-types/)).

I've tried a similar example btw. it works fine, but not with `filters`.

I hope the following snippets can help you.

```go
package main

import (
    "encoding/json"
    "fmt"
    "log"
    "net/http"

    "github.com/google/uuid"
    "github.com/morkid/paginate"
    "gorm.io/driver/mysql"
    "gorm.io/gorm"
    "gorm.io/gorm/logger"
)

// Movie struct
type Movie struct {
    ID   uuid.UUID `json:"id" gorm:"primary_key;type:varchar(36);column:id;unique;not null"`
    Title string    `json:"title"`
}

func (m *Movie) BeforeCreate(tx *gorm.DB) error {
    id, err := uuid.NewRandom()
    m.ID = id
    return err
}

func (Movie) TableName() string {
    return "movie"
}

func main() {
    dsn := "user:pass@tcp(127.0.0.1:3306)/mydb?charset=utf8mb4&parseTime=True&loc=Local"
    db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
        Logger: logger.Default.LogMode(logger.Info),
    })

    if nil != err {
        log.Fatal(err.Error())
        return
    }
    db.AutoMigrate(&Movie{})

    movies := []Movie{{Title: "The Hobbit"}, {Title: "Harry potter"}}

    tx := db.Begin()
    defer func() {
        if r := recover(); r != nil {
            tx.Rollback()
        }
    }()

    if err := tx.Create(&movies).Error; nil != err {
        tx.Rollback()
        log.Fatal(err.Error())
        return
    }

    if err := tx.Commit().Error; nil != err {
        tx.Rollback()
        log.Fatal(err.Error())
        return
    }

    pg := paginate.New()

    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        mod := db.Model(&Movie{})
        page := pg.With(mod).Request(r).Response(&[]Movie{})
        res, _ := json.Marshal(page)
        fmt.Fprintf(w, "%s", string(res))
    })

    log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Example response:
```json
{
    "items": [
        {
            "id": "05a036df-5c77-4711-8ea0-5320a806207e",
            "title": "The Hobbit"
        },
        {
            "id": "78ecc267-63d7-422c-ac16-484d5a786551",
            "title": "Harry potter"
        }
    ],
    "page": 0,
    "size": 10,
    "max_page": 1,
    "total_pages": 1,
    "total": 2,
    "last": false,
    "first": true,
    "visible": 2
}
```

Real data:
```
mysql> SELECT * FROM movie;
+--------------------------------------+--------------+
| id                                   | title        |
+--------------------------------------+--------------+
| 05a036df-5c77-4711-8ea0-5320a806207e | The Hobbit   |
| 78ecc267-63d7-422c-ac16-484d5a786551 | Harry potter |
+--------------------------------------+--------------+

```

I'm really sorry I can't help you so much for binary(16) conversion.  
maybe I'll take some time for the next feature.

**Comment by krewllobster** [comment]
Thank you for the examples!! The benefit of using Binary(16) primary keys vs varchar(36) is that it is much, much faster to look for in the db. Looks like I may need to do a double check on filters before passing them to pagination to make sure they're converted into the right values. I'll do some more digging. Much appreciated!
